### ISSUE TITLE
Can't find calc_pdc function

### ISSUE THREAD

**Issue by LiveFastCyYoung** [ReppCodes/propdayscov#1]
When trying to use the package I get the following error when trying to use the calc_pdc function...

"module 'propdayscov' has no attribute 'calc_pdc'

This is how I'm trying to use it...

import propdayscov as pdc
df_med = pdc.calc_pdc(indata=df, druglevel='N',mprocmode='Y')

**Comment by ReppCodes** [comment]
The module structure is a bit odd, granted.  Here's an example program.

```py
import pandas as pd
from propdayscov import propdayscov

indata = pd.read_excel('example.xlsx', sheet_name='example')
outdata = propdayscov.calc_pdc(indata=indata)
print(outdata)
```

**Comment by LiveFastCyYoung** [comment]
That is what I'm doing and it does not find the calc_pdc function within the module. I didn't include all of the intermediary code (such as importing Pandas and loading data into the dataframe df).

Even when looking at the functions in the module, calc_pdc does not appear.

**Comment by LiveFastCyYoung** [comment]
Can you show me what the output of dir(propdayscov) is for you? This is the output for me...

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'dt',
 'functools',
 'multiprocessing',
 'np',
 'pd',
 'sys']

**Comment by ReppCodes** [comment]
Based on your original comment, you have this structure:
import propdayscov as pdc
df_med = pdc.calc_pdc(indata=df, druglevel='N',mprocmode='Y')

You need:
from propdayscov import propdayscov as pdc
df_med = pdc.calc_pdc(indata=df, druglevel='N',mprocmode='Y')

Note the difference in import.  

Am I misunderstanding your question?

**Comment by LiveFastCyYoung** [comment]
I totally missed the from and then import. My bad. Thanks for the help! :)
